name: ci

on:
  push:
    branches:
      - master
      - dev/*

concurrency:
  group: build-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build artifacts
        run: ./gradlew build --no-daemon --stacktrace

      - name: Copy artifacts before uploading
        run: cp build/libs/PaperTweaks-*-all.jar ./PaperTweaks.jar

      - name: Generate SHA-256 hash
        run: sha256sum PaperTweaks.jar > PaperTweaks.jar.sha256


      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: PaperTweaks
          path: |
            PaperTweaks.jar
            PaperTweaks.jar.sha256
            LICENSE

      - name: Generate Build Summary
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;

            core.summary
              .addHeading('Download', 3)
              .addLink('PaperTweaks.zip', `https://nightly.link/${owner}/${repo}/actions/runs/${run_id}/PaperTweaks.zip`)
              .write();
